# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_video_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('normal', 'normal'), ('author', 'author')], default='normal', max_length=10),
        ),
    ]
